version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    image: kata-app
    restart: unless-stopped
    volumes:
      - ./:/app
    working_dir: /app
  composer:
    image: kata-app
    depends_on:
      - app
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
    restart: "no"
    entrypoint: composer
  phpunit:
    image: kata-app
    depends_on:
      - app
    restart: "no"
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
