version: '3'
services:
  composer:
    image: composer:1
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
    restart: never
  phpunit:
    build:
      context: ./
      dockerfile: docker/phpunit/Dockerfile
    image: phpunit
    container_name: finder-app
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
