version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    image: kata-app
    container_name: kata-app
    restart: unless-stopped
    volumes:
      - code:/app
    working_dir: /app
  composer:
    image: kata-app
    depends_on:
      - app
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - code:/app
    restart: "no"
    entrypoint: composer
  phpunit:
    image: kata-app
    depends_on:
      - app
    restart: "no"
    volumes:
      - code:/app
    entrypoint: vendor/bin/phpunit
  files:
    image: alpine:latest
    container_name: kata-app-files
    entrypoint: top
    restart: unless-stopped
    volumes:
      - code:/project

volumes:
  code:
